apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: jetstack
  pass_credentials_all: false
  password: ""
  url: https://charts.jetstack.io
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: redpanda
  pass_credentials_all: false
  password: ""
  url: https://charts.redpanda.com
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: itzg
  pass_credentials_all: false
  password: ""
  url: https://itzg.github.io/minecraft-server-charts/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: mojo2600
  pass_credentials_all: false
  password: ""
  url: https://mojo2600.github.io/pihole-kubernetes/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: k3
  pass_credentials_all: false
  password: ""
  url: https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: tailscale
  pass_credentials_all: false
  password: ""
  url: https://pkgs.tailscale.com/helmcharts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: kubernetes-dashboard
  pass_credentials_all: false
  password: ""
  url: https://kubernetes.github.io/dashboard/
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prequel
  pass_credentials_all: false
  password: ""
  url: https://prequel-dev.github.io/helm
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: runix
  pass_credentials_all: false
  password: ""
  url: https://helm.runix.net
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: penpot
  pass_credentials_all: false
  password: ""
  url: http://helm.penpot.app
  username: ""
