# Starship Configuration
# Catppuccin Mocha color palette with rich context information

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$kubernetes\
$docker_context\
$terraform\
$rust\
$golang\
$nodejs\
$python\
$package\
$aws\
$gcloud\
$memory_usage\
$jobs\
$cmd_duration\
$status\
$fill\
$battery\
$time\
$line_break\
$character"""

# Catppuccin Mocha Color Palette
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = "[|>](bold lavender)"
error_symbol = "[|>](bold red)"
vimcmd_symbol = "[<|](bold lavender)"

[directory]
style = "fg:mauve"
format = "[$path ]($style)"
truncation_length = 3
truncate_to_repo = true

[directory.substitutions]
"~/Repos/github.com/t-eckert" = "~"
"~/Repos/github.com/redpanda-data" = " rp"

[git_branch]
symbol = " "
style = "fg:lavender"
format = "[$symbol$branch ]($style)"

[git_status]
style = "fg:text"
format = "[$all_status$ahead_behind ]($style)"
conflicted = "[!${count}](fg:red)"
ahead = "[â†‘${count}](fg:peach)"
behind = "[â†“${count}](fg:peach)"
diverged = "[â†•${ahead_count}â†“${behind_count}](fg:peach)"
untracked = "[?${count}](fg:overlay2)"
stashed = "[*${count}](fg:yellow)"
modified = "[~${count}](fg:yellow)"
staged = "[+${count}](fg:green)"
renamed = "[Â»${count}](fg:blue)"
deleted = "[-${count}](fg:red)"

[kubernetes]
symbol = " "
style = "fg:sapphire"
format = '[$symbol$context ]($style)'
disabled = false

[[kubernetes.contexts]]
context_pattern = "gke_.*"
context_alias = "gke"

[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:.*"
context_alias = "eks"

[rust]
symbol = " "
style = "fg:peach"
format = "[$symbol$version ]($style)"

[golang]
symbol = " "
style = "fg:sapphire"
format = "[$symbol$version ]($style)"

[python]
symbol = " "
style = "fg:yellow"
format = '[$symbol$virtualenv ]($style)'

[aws]
symbol = " "
style = "fg:peach"
format = "[$symbol$profile ]($style)"

[gcloud]
symbol = " "
style = "fg:blue"
format = "[$symbol$project ]($style)"

[cmd_duration]
min_time = 2000
style = "fg:overlay2"
format = "[â± $duration ]($style)"

[status]
disabled = false
style = "fg:red"
success_style = "fg:green"
format = '[$symbol$int]($style) '
symbol = ""
success_symbol = " "
pipestatus = false
recognize_signal_code = false

[time]
disabled = false
format = '[$time ]($style)'
style = 'fg:overlay1'
time_format = '%R'
utc_time_offset = '0'

[battery]
disabled = false
format = '[$symbol$percentage ]($style)'
[[battery.display]]
threshold = 20
style = 'fg:red'
[[battery.display]]
threshold = 50
style = 'fg:yellow'
[[battery.display]]
threshold = 100
style = 'fg:green'

[memory_usage]
disabled = false
threshold = 75
format = '[${ram_pct} ]($style)'
style = 'fg:yellow'
symbol = ' '

[jobs]
symbol = 'âœ¦'
number_threshold = 1
format = '[$symbol$number ]($style)'
style = 'fg:blue'

[nodejs]
symbol = ' '
format = '[$symbol$version ]($style)'
style = 'fg:green'

[package]
symbol = 'ðŸ“¦ '
format = '[$symbol$version ]($style)'
style = 'fg:overlay2'
disabled = false

[terraform]
symbol = 'ðŸ’  '
format = '[$symbol$workspace ]($style)'
style = 'fg:mauve'

[docker_context]
symbol = ' '
format = '[$symbol$context ]($style)'
style = 'fg:blue'

[git_commit]
tag_symbol = ' ðŸ·  '
format = '[$hash$tag ]($style)'
style = 'fg:green'
only_detached = false
tag_disabled = false

[git_state]
format = '[$state( $progress_current/$progress_total) ]($style)'
style = 'fg:yellow'

[username]
show_always = false
format = '[$user]($style) '
style_user = 'fg:blue'
style_root = 'fg:red'

[hostname]
ssh_only = true
format = '[@$hostname ]($style)'
style = 'fg:green'

[fill]
symbol = ' '
